### ISSUE TITLE
Issueのテンプレート作成

### ISSUE THREAD

**Issue by yurihoka** [yurihoka/Beyond#1]
- Issueのテンプレートを作成する

**Comment by yurihoka** [comment]
Ref：
https://note.com/koushikagawa/n/n500e2f4d4019
■Issue項目
- 概要
- 目的
- タスク（目的を達成するためのタスクを記載）

**Comment by yurihoka** [comment]
@HidemichiShimura 
Issueテンプレートに記載する項目をリストアップしたので、確認お願いします！

**Comment by HidemichiShimura** [comment]
@yurihoka 
こっちも概ね一緒な感じです。
タイトルは提案してくれた感じで、Issueの先頭に[]をつける感じにしましょう

> [バグ]ログイン機能修正


Issueのテンプレートはこんな感じで

## 🎯 ゴール
> どうなっていればゴールか

- 

## 💡 背景
> なぜこのイシュー作成をしたのか

-

## 👣 ゴール達成手順
> どうすればゴールを達成できるか

1. 
2. 
3.

## 🤔 疑問点
> このイシューに関しての疑問点

- 

## 📝 メモ
> 他メンバーへの留意メモや個人的なメモなど

-

**Comment by yurihoka** [comment]
@HidemichiShimura 
確認ありがとうございます！
私の方でテンプレート作成を進めても問題ないですか？

**Comment by HidemichiShimura** [comment]
@yurihoka 
はーいお願いします
設定完了したらこのIssueはクローズしてください

**Comment by yurihoka** [comment]
@HidemichiShimura 
機能追加、バグ、リファクタの３種類のIssueテンプレートを作成予定でしたが、
テンプレート内容が同じなので、Issue内容に応じてタイトルの先頭を変える旨コメント記載して、１種類だけテンプレート作成しています！

**Comment by HidemichiShimura** [comment]
PRクローズしたのでこちらのissueもクローズします
