### ISSUE TITLE
[UI] ダッシュボードのワイヤーフレーム作成

### ISSUE THREAD

**Issue by yurihoka** [yurihoka/Beyond#14]
## 🎯 ゴール
> どうなっていればゴールか

- ダッシュボードのワイヤーフレーム作成

## 💡 背景
> なぜこのイシュー作成をしたのか

- ダッシュボードのワイヤーフレーム作成をするため

## 👣 ゴール達成手順
> どうすればゴールを達成できるか

- 簡単にダッシュボードのデザインイメージができれば○

## 🤔 疑問点
> このイシューに関しての疑問点

- 

## 📝 メモ
> 他メンバーへの留意メモや個人的なメモなど

-

**Comment by yurihoka** [comment]
Figma: https://www.figma.com/design/bXhXzXqtk3IR3Fo2ORs4B3/Beyond?node-id=0-1&t=O498yt5L6CiLUUFf-1

**Comment by HidemichiShimura** [comment]
@yurihoka 
> @HidemichiShimura ダッシュボードのワイヤーフレームを作成したので、お手隙で確認お願いします！ OKもらい次第Storybookでコンポーネント作成始めます。 Figma: https://www.figma.com/design/bXhXzXqtk3IR3Fo2ORs4B3/Beyond?node-id=0-1&t=O498yt5L6CiLUUFf-1

ワイヤーフレーム問題ないのでコンポーネント作成始めてください
このissueはクローズします！
