### ISSUE TITLE
アプリのワイヤーフレーム作成

### ISSUE THREAD

**Issue by yurihoka** [yurihoka/Beyond#2]
Figmaでアプリのワイヤーフレーム作成
- [ ] ログイン
- [ ] サインアップ
- [ ] ダッシュボード

**Comment by yurihoka** [comment]
@HidemichiShimura 
サインイン、サインアップのワイヤーフレームと、カラーパレットを作成したので確認お願いします！
https://www.figma.com/design/bXhXzXqtk3IR3Fo2ORs4B3/Beyond?node-id=0-1&t=6wnJQWtq5Bvrxgdd-1


以下後で相談させてください。
1. ブレイクポイントをどこにするか（現時点ではデスクトップ、タブレット、携帯の３種類にしています）
2. サインイン・アップはサードパーティーを使用するか（現時点ではGoogleのみワイヤーフレーム内に記載）
3. カラーはどれを使用するか

**Comment by HidemichiShimura** [comment]
@yurihoka 
ワイヤーフレーム作成ありがとうございます！
 Figmaのアクセス権限リクエストしたので確認お願いしますー！
確認してから上記の質問まとめて回答しますね 👍🏻

**Comment by yurihoka** [comment]
@HidemichiShimura 
失礼しました！
リクエスト承認と編集権限もつけたのであわせて確認お願いします！

**Comment by HidemichiShimura** [comment]
@yurihoka 
権限付与ありがとうございます！

> ブレイクポイントをどこにするか（現時点ではデスクトップ、タブレット、携帯の３種類にしています）

これで行こうと思います！

- モバイル: 480px
- タブレット: 768px
- PC: 1280px

>サインイン・アップはサードパーティーを使用するか（現時点ではGoogleのみワイヤーフレーム内に記載）

使用する予定です！
ですが、工数の関係で実装自体は後回しにしようかと思ってます。

>カラーはどれを使用するか

ワイヤーフレームになるカラーで問題ないです！ありがとうございます！

**Comment by yurihoka** [comment]
@HidemichiShimura 
おっけーです！じゃあこのIssueはクローズしておきます！
